version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"     # options: daily/weekly/monthly
    target-branch: "main"
    reviewers:
      - "bkimminich"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "express-jwt"
        versions: ["0.1.3"]
      - dependency-name: "sanitize-html"
        versions: ["1.4.2"]
      - dependency-name: "unzipper"
        versions: ["0.9.15"]
      - dependency-name: "jsonwebtoken"
        versions: ["0.4.0"]
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "bkimminich"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
