name: DAST - OWASP ZAP Scan

on:
  workflow_dispatch:        # Manual trigger
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://juice-shop.herokuapp.com"
          rules_file_name: "owasp_rules.yml"
          fail_on_risk: "high"
          format: "html"
