name: OWASP Dependency-Check Scan

on:
  workflow_dispatch:  # allows manual trigger
  push:
    branches: [ "main" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Check Scan
        uses: jeremylong/DependencyCheck-action@v2
        with:
          project: JuiceShop
          scan-path: .
          format: HTML
          fail-on-error: true

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
