name: OWASP Dependency-Check Scan

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ "main" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Dependency-Check scan
      - name: Dependency Check Scan
        uses: owasp/dependency-check-action@v1
        with:
          project: JuiceShop
          scan-path: .
          format: HTML
          fail-on-error: true

      # Step 3: Upload HTML report as artifact
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
