name: "Trivy SCA Scan - Juice Shop"

on:
  workflow_dispatch:    # Manual trigger
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  trivy-sca:
    name: Trivy SCA Scan (Dependencies)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write  # Required for SARIF upload

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Trivy SCA scan and output SARIF
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif

      # Step 3: Upload SARIF results to GitHub Security Tab
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # Step 4: Upload SARIF as downloadable artifact
      - name: Upload SARIF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sca-sarif
          path: trivy-results.sarif
