name: "ZAP Baseline Scan"

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  zap_scan:
    name: Scan OWASP Juice Shop (Heroku)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run ZAP Baseline Scan
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://preview.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'

      # Step 3: Upload ZAP Report as artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.json
